name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ./vcpkg
          C:\Users\runneradmin\AppData\Local\vcpkg
        key: ${{ runner.os }}-vcpkg


    - uses: actions/checkout@v2

    - name : install msys2
      run: choco install msys2

    - name: Bootstrap vspkg
      run: |
        git clone --depth=1 https://github.com/TyOverby/vcpkg.git
        vcpkg\bootstrap-vcpkg.bat

    - name: Install packages
      run: |
        vcpkg\vcpkg install libpng:x86-windows-static

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

