name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ./vcpkg
          C:\Users\runneradmin\AppData\Local\vcpkg
        key: ${{ runner.os }}-vcpkg


    - uses: actions/checkout@v2

    - name : Pacman
      run: | 
        pacman-key --init
        pacman-key --populate msys2
        pacman-key --refresh-keys



    - name: Bootstrap vspkg
      run: |
        git clone --depth=1 --branch patch-7 https://github.com/Neumann-A/vcpkg.git
        vcpkg\bootstrap-vcpkg.bat

    - name: Install packages
      run: |
        vcpkg\vcpkg install libpng:x86-windows-static
        vcpkg\vcpkg install eigen3:x86-windows-static
        vcpkg\vcpkg install boost:x86-windows-static

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

