name: OSX-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest 

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install cmake pkg-config eigen libpng qt guile@2 boost tree

    - name: Build Project
      run: |
        export PKG_CONFIG_PATH="/usr/local/opt/guile@2/lib/pkgconfig:$PKG_CONFIG_PATH"
        export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig:$PKG_CONFIG_PATH"
        export Qt5Core_DIR=/usr/local/opt/qt/lib/cmake/Qt5Core
        mkdir build
        cd build
        cmake ..
        make -j4

    - name: Test
      continue-on-error: true
      run: ./build/libfive/test/libfive-test

    - name: Tree
      run: tree ./build

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts.zip
        path: |
          ./studio/Studio
          ./libfive/src/libfive.dylib
          ./libfive/bind/libfive-guile.so
