name: OSX-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest 

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install cmake pkg-config eigen libpng qt guile boost

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j4

    - name: Test
      run: ./build/libfive/test/libfive-test
