name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/cache@v2
      id: vcpkg-cache
      with:
        path: |
          vcpkg
          C:\Users\runneradmin\AppData\Local\vcpkg
        key: ${{ runner.os }}-vcpkg-cache-min

    - uses: actions/checkout@v2

    - name: Bootstrap vspkg
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg 
        git checkout 2020.04
        cd ..
        vcpkg\bootstrap-vcpkg.bat

    - name: Install packages
      run: |
        vcpkg\vcpkg install libpng:x86-windows-static 
        vcpkg\vcpkg install boost-algorithm:x86-windows-static 
        vcpkg\vcpkg install boost-lockfree:x86-windows-static 
        vcpkg\vcpkg install boost-bimap:x86-windows-static 
        vcpkg\vcpkg install boost-numeric:x86-windows-static 
        vcpkg\vcpkg install eigen3:x86-windows-static

#    - name: Build
#      run: |
#        md build
#        cd build
#        cmake -DCMAKE_TOOLCHAIN_FILE="..\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x86-windows-static" -G "Visual Studio 15 2017" ..


