name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ./vcpkg
          C:\Users\runneradmin\AppData\Local\vcpkg
        key: ${{ runner.os }}-vcpkg

    - uses: actions/checkout@v2

    - name: Bootstrap vspkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg 
        git checkout 6bf5adff937abd9bf09fb1c3fda40b5f566f8acd
        cd ..
        vcpkg\bootstrap-vcpkg.bat

    - name: Install packages
      run: |
        vcpkg\vcpkg install libpng:x86-windows-static boost:x86-windows-static eigen3:x86-windows-static

    - name: Build
      run: |
        md build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="..\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x86-windows-static" -G "Visual Studio 15 2017" ..


